CONFIG_BT=n

CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_STACK_NEXT=n
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
CONFIG_DEPRECATION_TEST=y

CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
CONFIG_CDC_ACM_SERIAL_ENABLE_AT_BOOT=y
CONFIG_CDC_ACM_SERIAL_MANUFACTURER_STRING="TeamIO"
CONFIG_CDC_ACM_SERIAL_PRODUCT_STRING="RDB UART Test"
CONFIG_CDC_ACM_SERIAL_VID=0x303A
CONFIG_CDC_ACM_SERIAL_PID=0x4010
