CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
CONFIG_CDC_ACM_SERIAL_ENABLE_AT_BOOT=y
CONFIG_CDC_ACM_SERIAL_MANUFACTURER_STRING="TeamIO"
CONFIG_CDC_ACM_SERIAL_PRODUCT_STRING="RDB UART Test"
CONFIG_CDC_ACM_SERIAL_VID=0x303A
CONFIG_CDC_ACM_SERIAL_PID=0x4010
