CONFIG_CPP=y
CONFIG_STD_CPP2B=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_GLIBCXX_LIBCPP=y

# CONFIG_BT=y
# CONFIG_BT_PERIPHERAL=y
# CONFIG_BT_MAX_PAIRED=1
# CONFIG_BT_DEVICE_NAME="RhythmDoctorButton"

# CONFIG_BT_KEYS_OVERWRITE_OLDEST=y
# CONFIG_BT_SMP=y
# CONFIG_BT_SETTINGS=y
# CONFIG_BT_BONDABLE=y
# CONFIG_BT_SETTINGS_CCC_STORE_ON_WRITE=y
# CONFIG_BT_SETTINGS_CCC_LAZY_LOADING=n
# CONFIG_SETTINGS=y
# CONFIG_FLASH=y
# CONFIG_FLASH_MAP=y
# CONFIG_NVS=y
# CONFIG_SETTINGS_NVS=y

# CONFIG_BT_LIM_ADV_TIMEOUT=180

# CONFIG_BT_BAS=y
# CONFIG_BT_DIS=y
# CONFIG_BT_DIS_PNP=n
# CONFIG_BT_DIS_MODEL_NUMBER=y
# CONFIG_BT_DIS_MODEL_NUMBER_STR="v1.0.0"
# CONFIG_BT_DIS_MANUF_NAME=y
# CONFIG_BT_DIS_MANUF_NAME_STR="TeamIO"
# CONFIG_BT_DIS_SERIAL_NUMBER=y
# CONFIG_BT_DIS_SERIAL_NUMBER_STR="0xAABBCCDD"

# CONFIG_BT_DEVICE_APPEARANCE=961 
# CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6    
# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=18    
# CONFIG_BT_PERIPHERAL_PREF_LATENCY=10   
# CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=200
# CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y

CONFIG_GPIO=y
CONFIG_ADC=y
CONFIG_PWM=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
# CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
# CONFIG_SYSTEM_CLOCK_NO_WAIT=y

CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_HID_SUPPORT=y
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
CONFIG_CDC_ACM_SERIAL_ENABLE_AT_BOOT=y
CONFIG_CDC_ACM_SERIAL_MANUFACTURER_STRING="TeamIO"
CONFIG_CDC_ACM_SERIAL_PRODUCT_STRING="RDB CDC Console"
CONFIG_CDC_ACM_SERIAL_VID=0x303A
CONFIG_CDC_ACM_SERIAL_PID=0x4010

CONFIG_BUILD_OUTPUT_UF2=y
CONFIG_FLASH_LOAD_OFFSET=0x26000
# CONFIG_USE_DT_CODE_PARTITION=y
